<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PetsSeeder extends Seeder
{
    public function run(): void
    {
        $adminId = cache()->get('admin_id');

        $pets = [
            // Chó
            [
                'Ma_thu_cung'    => Str::uuid()->toString(),
                'Ma_hien_thi'    => 'PET-001',
                'Ten'            => 'Bông',
                'Loai'           => 'cho',
                'Giong'          => 'Poodle',
                'Nhom_tuoi'      => 'nho',
                'Can_nang'       => 3.5,
                'Gioi_tinh'      => 'cai',
                'Da_tiem_phong'  => true,
                'Da_triet_san'   => false,
                'Trang_thai'     => 'san_sang',
                'Vi_tri'         => 'noi_tru',
                'Than_thien_nguoi' => true,
                'Than_thien_cho'   => true,
                'Than_thien_meo'   => false,
                'Che_do_an_dac_biet' => null,
                'Ngay_tiep_nhan' => '2026-04-10',
                'Phi_nhan_nuoi'  => 500000,
                'Noi_bat'        => true,
                'Mo_ta'          => 'Bông là bé Poodle trắng muốt, rất thân thiện và lanh lợi. Bé thích được vuốt ve và chơi đùa.',
                'Nguoi_phu_trach' => $adminId,
                'Anh_dai_dien'   => null,
            ],
            [
                'Ma_thu_cung'    => Str::uuid()->toString(),
                'Ma_hien_thi'    => 'PET-002',
                'Ten'            => 'Corgi Cam',
                'Loai'           => 'cho',
                'Giong'          => 'Corgi Pembroke',
                'Nhom_tuoi'      => 'truong_thanh',
                'Can_nang'       => 12.0,
                'Gioi_tinh'      => 'duc',
                'Da_tiem_phong'  => true,
                'Da_triet_san'   => true,
                'Trang_thai'     => 'san_sang',
                'Vi_tri'         => 'noi_tru',
                'Than_thien_nguoi' => true,
                'Than_thien_cho'   => true,
                'Than_thien_meo'   => true,
                'Che_do_an_dac_biet' => null,
                'Ngay_tiep_nhan' => '2026-03-20',
                'Phi_nhan_nuoi'  => 800000,
                'Noi_bat'        => true,
                'Mo_ta'          => 'Corgi Cam là bé rất năng động, thích chạy nhảy và vui chơi. Bé hợp với gia đình có trẻ em.',
                'Nguoi_phu_trach' => $adminId,
                'Anh_dai_dien'   => null,
            ],
            [
                'Ma_thu_cung'    => Str::uuid()->toString(),
                'Ma_hien_thi'    => 'PET-003',
                'Ten'            => 'Phốc Đen',
                'Loai'           => 'cho',
                'Giong'          => 'Phốc sóc',
                'Nhom_tuoi'      => 'nho',
                'Can_nang'       => 2.8,
                'Gioi_tinh'      => 'duc',
                'Da_tiem_phong'  => false,
                'Da_triet_san'   => false,
                'Trang_thai'     => 'chua_san_sang',
                'Vi_tri'         => 'phong_kham',
                'Than_thien_nguoi' => true,
                'Than_thien_cho'   => null,
                'Than_thien_meo'   => null,
                'Che_do_an_dac_biet' => 'Đang điều trị viêm da, cần thức ăn đặc biệt không có ngũ cốc',
                'Ngay_tiep_nhan' => '2026-05-15',
                'Phi_nhan_nuoi'  => 300000,
                'Noi_bat'        => false,
                'Mo_ta'          => 'Phốc Đen đang được điều trị và sẽ sớm sẵn sàng cho nhận nuôi.',
                'Nguoi_phu_trach' => $adminId,
                'Anh_dai_dien'   => null,
            ],
            [
                'Ma_thu_cung'    => Str::uuid()->toString(),
                'Ma_hien_thi'    => 'PET-004',
                'Ten'            => 'Husky Xám',
                'Loai'           => 'cho',
                'Giong'          => 'Siberian Husky',
                'Nhom_tuoi'      => 'truong_thanh',
                'Can_nang'       => 25.0,
                'Gioi_tinh'      => 'cai',
                'Da_tiem_phong'  => true,
                'Da_triet_san'   => false,
                'Trang_thai'     => 'san_sang',
                'Vi_tri'         => 'noi_tru',
                'Than_thien_nguoi' => true,
                'Than_thien_cho'   => true,
                'Than_thien_meo'   => false,
                'Che_do_an_dac_biet' => 'Cần chế độ ăn cao protein, ít carb',
                'Ngay_tiep_nhan' => '2026-02-28',
                'Phi_nhan_nuoi'  => 1200000,
                'Noi_bat'        => false,
                'Mo_ta'          => 'Husky Xám rất thông minh và năng động. Cần không gian rộng để vận động.',
                'Nguoi_phu_trach' => $adminId,
                'Anh_dai_dien'   => null,
            ],
            [
                'Ma_thu_cung'    => Str::uuid()->toString(),
                'Ma_hien_thi'    => 'PET-005',
                'Ten'            => 'Golden Boy',
                'Loai'           => 'cho',
                'Giong'          => 'Golden Retriever',
                'Nhom_tuoi'      => 'truong_thanh',
                'Can_nang'       => 30.0,
                'Gioi_tinh'      => 'duc',
                'Da_tiem_phong'  => true,
                'Da_triet_san'   => true,
                'Trang_thai'     => 'da_nhan_nuoi',
                'Vi_tri'         => 'noi_tru',
                'Than_thien_nguoi' => true,
                'Than_thien_cho'   => true,
                'Than_thien_meo'   => true,
                'Che_do_an_dac_biet' => null,
                'Ngay_tiep_nhan' => '2026-01-15',
                'Phi_nhan_nuoi'  => 1500000,
                'Noi_bat'        => false,
                'Mo_ta'          => 'Golden Boy đã được nhận nuôi. Bé rất hiền lành và yêu trẻ em.',
                'Nguoi_phu_trach' => $adminId,
                'Anh_dai_dien'   => null,
            ],
            // Mèo
            [
                'Ma_thu_cung'    => Str::uuid()->toString(),
                'Ma_hien_thi'    => 'PET-006',
                'Ten'            => 'Miu',
                'Loai'           => 'meo',
                'Giong'          => 'Mèo Anh lông ngắn',
                'Nhom_tuoi'      => 'truong_thanh',
                'Can_nang'       => 4.5,
                'Gioi_tinh'      => 'cai',
                'Da_tiem_phong'  => true,
                'Da_triet_san'   => true,
                'Trang_thai'     => 'san_sang',
                'Vi_tri'         => 'noi_tru',
                'Than_thien_nguoi' => true,
                'Than_thien_cho'   => false,
                'Than_thien_meo'   => true,
                'Che_do_an_dac_biet' => null,
                'Ngay_tiep_nhan' => '2026-03-01',
                'Phi_nhan_nuoi'  => 600000,
                'Noi_bat'        => true,
                'Mo_ta'          => 'Miu là cô nàng mèo Anh lông ngắn màu xám xanh, tính cách điềm tĩnh và sang trọng.',
                'Nguoi_phu_trach' => $adminId,
                'Anh_dai_dien'   => null,
            ],
            [
                'Ma_thu_cung'    => Str::uuid()->toString(),
                'Ma_hien_thi'    => 'PET-007',
                'Ten'            => 'Chân Ngắn',
                'Loai'           => 'meo',
                'Giong'          => 'Munchkin',
                'Nhom_tuoi'      => 'nho',
                'Can_nang'       => 2.2,
                'Gioi_tinh'      => 'duc',
                'Da_tiem_phong'  => false,
                'Da_triet_san'   => false,
                'Trang_thai'     => 'chua_san_sang',
                'Vi_tri'         => 'phong_kham',
                'Than_thien_nguoi' => true,
                'Than_thien_cho'   => null,
                'Than_thien_meo'   => true,
                'Che_do_an_dac_biet' => null,
                'Ngay_tiep_nhan' => '2026-05-20',
                'Phi_nhan_nuoi'  => 200000,
                'Noi_bat'        => false,
                'Mo_ta'          => 'Chân Ngắn là bé Munchkin cực kỳ đáng yêu, đang được chăm sóc và tiêm chủng.',
                'Nguoi_phu_trach' => $adminId,
                'Anh_dai_dien'   => null,
            ],
            [
                'Ma_thu_cung'    => Str::uuid()->toString(),
                'Ma_hien_thi'    => 'PET-008',
                'Ten'            => 'Maine Khổng Lồ',
                'Loai'           => 'meo',
                'Giong'          => 'Maine Coon',
                'Nhom_tuoi'      => 'gia',
                'Can_nang'       => 7.0,
                'Gioi_tinh'      => 'duc',
                'Da_tiem_phong'  => true,
                'Da_triet_san'   => true,
                'Trang_thai'     => 'san_sang',
                'Vi_tri'         => 'noi_tru',
                'Than_thien_nguoi' => true,
                'Than_thien_cho'   => true,
                'Than_thien_meo'   => true,
                'Che_do_an_dac_biet' => 'Cần thức ăn dành cho mèo cao tuổi',
                'Ngay_tiep_nhan' => '2026-02-10',
                'Phi_nhan_nuoi'  => 900000,
                'Noi_bat'        => false,
                'Mo_ta'          => 'Maine Khổng Lồ là bé mèo già, hiền hậu và thích cuộn tròn trên lòng người.',
                'Nguoi_phu_trach' => $adminId,
                'Anh_dai_dien'   => null,
            ],
            // Khác
            [
                'Ma_thu_cung'    => Str::uuid()->toString(),
                'Ma_hien_thi'    => 'PET-009',
                'Ten'            => 'Thỏ Trắng',
                'Loai'           => 'khac',
                'Giong'          => 'Thỏ Holland Lop',
                'Nhom_tuoi'      => 'nho',
                'Can_nang'       => 1.8,
                'Gioi_tinh'      => 'cai',
                'Da_tiem_phong'  => false,
                'Da_triet_san'   => false,
                'Trang_thai'     => 'dang_cuu_ho',
                'Vi_tri'         => 'phong_kham',
                'Than_thien_nguoi' => true,
                'Than_thien_cho'   => false,
                'Than_thien_meo'   => false,
                'Che_do_an_dac_biet' => 'Ăn cỏ timothy và rau xanh, không ăn ngũ cốc',
                'Ngay_tiep_nhan' => '2026-05-28',
                'Phi_nhan_nuoi'  => 0,
                'Noi_bat'        => false,
                'Mo_ta'          => 'Thỏ Trắng đang được cứu hộ và chăm sóc sức khỏe ban đầu.',
                'Nguoi_phu_trach' => $adminId,
                'Anh_dai_dien'   => null,
            ],
            [
                'Ma_thu_cung'    => Str::uuid()->toString(),
                'Ma_hien_thi'    => 'PET-010',
                'Ten'            => 'Ham Béo',
                'Loai'           => 'khac',
                'Giong'          => 'Hamster Syrian',
                'Nhom_tuoi'      => 'truong_thanh',
                'Can_nang'       => 0.15,
                'Gioi_tinh'      => 'duc',
                'Da_tiem_phong'  => false,
                'Da_triet_san'   => false,
                'Trang_thai'     => 'da_mat',
                'Vi_tri'         => 'phong_kham',
                'Than_thien_nguoi' => true,
                'Than_thien_cho'   => false,
                'Than_thien_meo'   => false,
                'Che_do_an_dac_biet' => null,
                'Ngay_tiep_nhan' => '2026-04-01',
                'Phi_nhan_nuoi'  => 0,
                'Noi_bat'        => false,
                'Mo_ta'          => 'Ham Béo đã không qua khỏi do sức khỏe yếu khi tiếp nhận.',
                'Nguoi_phu_trach' => $adminId,
                'Anh_dai_dien'   => null,
            ],
        ];

        $petIds = [];
        foreach ($pets as $pet) {
            $pet['Ngay_tao']       = now();
            $pet['Ngay_cap_nhat']  = now();
            DB::table('pets')->insert($pet);
            $petIds[$pet['Ma_hien_thi']] = $pet['Ma_thu_cung'];
        }

        cache()->put('pet_ids', $petIds, 600);

        $this->command->info('✅ PetsSeeder hoàn thành: 10 thú cưng.');
    }
}
